### ISSUE TITLE
Text representative of Prerequisites to be moved

### ISSUE THREAD

**Issue by bpiereck** [ELIXIR-FAIR-Training/FAIR-training-handbook#10]
https://github.com/ELIXIR-FAIR-Training/FAIR-training-handbook/blob/4f64b5661c3d4cd6c22fbb4feb2d6dda54ac9ce7/docs/chapters/chapter_07.md?plain=1#L20

In this line the previous chapters 2 and 3 are referenced as necessary. And the chapter 8 as complementary reading. I suggest that the portion referring to 2 and 3 can be exclusively in the PREREQUISITES part of the text avoiding repetition. While maintaining the chapter 8 suggested for complementary reading  about licensing.

**Comment by burkemlou** [comment]
I've edited this chapter so that chapters 2 and 3 are only mentioned in the prerequisites. I've also removed 'Related chapters' as discussed at the Biohackathon.
