### ISSUE TITLE
Session to be removed

### ISSUE THREAD

**Issue by bpiereck** [ELIXIR-FAIR-Training/FAIR-training-handbook#11]
https://github.com/ELIXIR-FAIR-Training/FAIR-training-handbook/blob/4f64b5661c3d4cd6c22fbb4feb2d6dda54ac9ce7/docs/chapters/chapter_07.md?plain=1#L29

The following session is not part of the structure anymore, therefore should be kept out of the chapter.

**Comment by burkemlou** [comment]
Removed this section.
