### ISSUE TITLE
need to format references

### ISSUE THREAD

**Issue by hchiapello** [ELIXIR-FAIR-Training/FAIR-training-handbook#15]
https://github.com/ELIXIR-FAIR-Training/FAIR-training-handbook/blob/500270303d714ab5b1487eab75cd08e6360b4ae3/docs/chapters/chapter_06.md?plain=1#L95

**Comment by GeertvanGeest** [comment]
You can use references by adding a bibtex reference (e.g. export with zotero/mendely) to `references.bib`. After that you can cite in the text with `[@firstauthor_year]`. Where `firstauthor_year` is the name of the reference in the bibtex. A wrote a bit more on this in the [readme](https://github.com/ELIXIR-FAIR-Training/FAIR-training-handbook#adding-references).

**Comment by GeertvanGeest** [comment]
Possibly best to assign yourself to this issue @hchiapello ?

**Comment by hchiapello** [comment]
ok just done !
