### ISSUE TITLE
Chapter 5: Is this ORCID video correct?

### ISSUE THREAD

**Issue by burkemlou** [ELIXIR-FAIR-Training/FAIR-training-handbook#36]
https://github.com/ELIXIR-FAIR-Training/FAIR-training-handbook/blob/d1a788c62471dbbdeca35db28565f30e5f7dd192/docs/chapters/chapter_05.md?plain=1#L81

Should this be pointing to this video instead?

https://vimeo.com/236778203

**Comment by bpiereck** [comment]
I believe the other one is more engaging, and is also a official video of the ORCID website, therefore I believe we should keep.
