### ISSUE TITLE
Chapter 8: add paragraph about licenses alternative to CC

### ISSUE THREAD

**Issue by Lisanna** [ELIXIR-FAIR-Training/FAIR-training-handbook#45]
Work on chapter 8 in the Google Doc: [link](https://docs.google.com/document/d/1R2PsE5MWMl-wsCSYUi9iNCsgCz8FeKNTl22DqxtXjnY/edit)

**Comment by Lisanna** [comment]
@annaswan1 I believe this is done, but I'll wait for your revision to close the issue

**Comment by annaswan1** [comment]
@Lisanna All done, thank you
